### ISSUE TITLE
Chain head is not set yet. Permit all.

### ISSUE THREAD

**Issue by frode88** [gluwa/CreditcoinDocs-Mainnet#1]
Hi.
How to fix this issue? thank you

wtooth-validator-default | [2020-02-01 22:48:41.229 DEBUG    permission_verifier] Chain head is not set yet. Permit all.

**Comment by MrAusnadian** [comment]
See https://medium.com/creditcoin-foundation/updating-creditcoin-nodes-f584a7e645f1 for information on how to download a snapshot of the blockchain and update your docker images.

**Comment by frode88** [comment]
Hi., thank mean the chain in sync? this is why we see this massage?
