### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by frode88** [gluwa/CreditcoinDocs-Mainnet#2]
Hi.
There is anyway to stop mining so the chain can sync faster? Still on 311998. Thank you.

**Comment by MrAusnadian** [comment]
There is no way to disable mining in the current implementation, the only way to speed up syncing is to download an up-to-date snapshot. With that in mind, we've provided an updated snapshot of the blockchain which can be downloaded here:

Torrent - https://drive.google.com/a/gluwa.com/file/d/1y1Y2Owlv1q89lFoPTQo1HfDNSY3Rehnu/view?usp=sharing
Magnet - magnet:?xt=urn:btih:431875a15ea6a50280faee41bfcc15d5718b5085&dn=creditcoin-block-volume.tar.gz&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80
