### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by frode88** [gluwa/CreditcoinDocs-Mainnet#3]
Hi.
I have issue with node dosent want to Sync. Any Idea how to solve this issue? whats the path to this rm plugins/progress.txt?

thank you.

![Skjermbilde](https://user-images.githubusercontent.com/22121200/73734792-7e41b000-473e-11ea-82ae-241e68ed2eb1.PNG)

**Comment by MrAusnadian** [comment]
There is no way to disable mining in the current implementation, the only way to speed up syncing is to download an up-to-date snapshot. With that in mind, we've provided an updated snapshot of the blockchain which can be downloaded here:

Torrent - https://drive.google.com/a/gluwa.com/file/d/1y1Y2Owlv1q89lFoPTQo1HfDNSY3Rehnu/view?usp=sharing
Magnet - magnet:?xt=urn:btih:431875a15ea6a50280faee41bfcc15d5718b5085&dn=creditcoin-block-volume.tar.gz&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80
