### ISSUE TITLE
How To send coins

### ISSUE THREAD

**Issue by frode88** [gluwa/CreditcoinDocs-Mainnet#9]
Hi.
there is anyway to send coin on ethereum Network? any link shows how? thank you

**Comment by taelimoh** [comment]
You cannot send Creditcoin on the mainnet to the Ethereum Network.

**Comment by frode88** [comment]
hi. Thank you for fast answer. That mean I cant sell coin on bittrex?

**Comment by taelimoh** [comment]
Short Answer: No, you cannot.

Long Answer: Creditcoin distributed on the Erthereum network (G-CRE) can be converted to the Creditcoin on the mainnet, but not the other way around. Bittrex Global has only listed G-CRE at the moment. Thus, you cannot sell the mined Creditcoin on the exchange.
